Repository Meezzi/mongbi-app, pull requests merged in 2025-07, with the labels that each got.

#304 [History] UT 피드백 반영 - 스크롤 포커스 기능 추가
  lib/presentation/history/history_page.dart
  lib/presentation/history/widgets/calendar.dart
  lib/presentation/history/widgets/calendar_cell.dart
  lib/presentation/history/widgets/history_body.dart
  lib/presentation/history/widgets/history_item.dart
  lib/presentation/history/widgets/history_list.dart
  lib/presentation/history/widgets/history_notice.dart
  lib/presentation/history/widgets/measure_size.dart
Labels: feat

#300 [Remind] 리마인드 동기화 에러 수정 및 각종 에러 수정
  lib/core/analytics/analytics_helper.dart
  lib/presentation/auth/social_login_page.dart
  lib/presentation/challenge/challenge_page.dart
  lib/presentation/dream/widgets/mood_selection_row.dart
  lib/presentation/home/home_page.dart
  lib/presentation/onboarding/onbording_page.dart
  lib/presentation/remind/remind_time_setting_page.dart
  lib/presentation/remind/remind_time_time_setting_page.dart
  lib/presentation/remind/view_model/remind_time_setting_view_model.dart
  lib/presentation/setting/alarm_setting_page.dart
  lib/presentation/setting/models/alarm_setting_state.dart
  lib/presentation/setting/nickname_input_page.dart
  lib/presentation/setting/profile_setting_page.dart
  lib/presentation/setting/setting_page.dart
  lib/presentation/setting/view_models/alarm_setting_view_model.dart
  lib/presentation/setting/view_models/nickname_setting_view_model.dart
  lib/presentation/setting/widgets/logout_account_modal.dart
  lib/presentation/splash/splash_page.dart
  pubspec.lock
Labels: fix

#308 [Core] analytics 경로 업데이트
  lib/presentation/auth/social_login_page.dart
  lib/presentation/challenge/challenge_page.dart
  lib/presentation/home/home_page.dart
  lib/presentation/onboarding/onbording_page.dart
  lib/presentation/remind/remind_time_setting_page.dart
  lib/presentation/remind/remind_time_time_setting_page.dart
  lib/presentation/setting/alarm_setting_page.dart
  lib/presentation/setting/nickname_input_page.dart
  lib/presentation/setting/profile_setting_page.dart
  lib/presentation/setting/setting_page.dart
  lib/presentation/setting/widgets/logout_account_modal.dart
  lib/presentation/splash/splash_page.dart
Labels: bug

#310 [Home] 몽비 이미지 파일 이름 수정
  lib/presentation/home/widgets/challenge_card.dart
  lib/presentation/home/widgets/give_up_confirm_bottom_sheet.dart
Labels: feat

#320 [Docs] README 수정
  README.md
Labels: documentation

#318 [Alarm] FCM 기초 셋팅
  lib/core/set_up_fcm.dart
  lib/main.dart
Labels: feat

#314 [Remind] 리마인드 건너뛰기 기능 추가
  lib/presentation/remind/remind_time_setting_page.dart
Labels: feat

#324 [Core] 안드로이드 배포 관련 준비
  android/app/build.gradle.kts
  android/app/proguard-rules.pro
  android/app/src/main/res/drawable/ic_mongbi_icon.png
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  assets/images/mongbi_brave.webp
  assets/images/mongbi_happy.webp
  assets/images/mongbi_joyful.webp
  assets/images/mongbi_sad.webp
  assets/images/mongbi_surprised.webp
  lib/core/auth_interceptor.dart
  lib/core/main_scaffold.dart
  lib/main.dart
  lib/presentation/remind/remind_time_setting_page.dart
  lib/presentation/remind/remind_time_time_setting_page.dart
  lib/presentation/remind/view_model/remind_time_setting_view_model.dart
  lib/presentation/setting/nickname_input_page.dart
  pubspec.lock
  pubspec.yaml
Labels: fix

#328 [Core] iOS에서 Firebase/Messaging 버전 업데이트를 위해 Podfile.lock 변경
  ios/Podfile.lock
  pubspec.lock
Labels: feat

#332 [Dream] 서버 과부화 에러 스낵바 표시
  lib/presentation/dream/dream_analysis_loading_page.dart
  lib/presentation/dream/dream_interpretation_page.dart
Labels: bug

#338 [Core] 난독화 관련 코드 제거
  pubspec.yaml
Labels: fix

#347 [Core] 배경음악 재생시 이미 dispose가 되었는데 ref 사용으로 인한 강제종료
  lib/main.dart
Labels: bug

#348 [Core] 코드 난독화 재 적용 및 배포 관련 안드로이드 버전 강화
  android/app/build.gradle.kts
  android/app/proguard-rules.pro
  android/app/src/main/AndroidManifest.xml
  android/build.gradle.kts
  android/gradle.properties
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: feat

#345 [Core] 반응형 UI
  lib/core/main_scaffold.dart
  lib/core/responsive_layout.dart
  lib/core/router.dart
  lib/presentation/challenge/challenge_intro_page.dart
  lib/presentation/challenge/challenge_page.dart
  lib/presentation/challenge/widgets/mongbi_dialog.dart
  lib/presentation/dream/dream_analysis_loading_page.dart
  lib/presentation/dream/dream_analysis_result_page.dart
  lib/presentation/dream/dream_intro_page.dart
  lib/presentation/dream/dream_write_page.dart
  lib/presentation/history/widgets/calendar.dart
  lib/presentation/history/widgets/calendar_bottom_sheet.dart
  lib/presentation/history/widgets/calendar_cell.dart
  lib/presentation/history/widgets/calendar_change_button.dart
  lib/presentation/setting/setting_page.dart
  lib/presentation/setting/widgets/logout_account_modal.dart
  lib/presentation/setting/widgets/remove_accont_modal.dart
  lib/presentation/setting/widgets/setting_user_info_header.dart
  lib/presentation/statistics/statistics_page.dart
  lib/presentation/statistics/widgets/month_statistics.dart
  lib/presentation/statistics/widgets/month_year_picker.dart
  lib/presentation/statistics/widgets/month_year_picker_button.dart
  lib/presentation/statistics/widgets/mood_state_info_modal.dart
  lib/presentation/statistics/widgets/year_statistics.dart
  lib/presentation/terms/widgets/terms_bottom_sheet_layout_widget.dart
  lib/presentation/terms/widgets/terms_checkbox_widget.dart
  lib/presentation/terms/widgets/terms_text_widget.dart
Labels: feat

#349 모든 기기 세로 모드 고정 설정
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Info.plist
  lib/main.dart
  pubspec.lock
Labels: documentation, feat

#351 [Core] 안드로이드 결제 권한 추가
  android/app/src/main/AndroidManifest.xml
Labels: feat

#353 [Payment] ios 결제 권한 추가
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Runner.entitlements
Labels: feat

#357 [Core] 인앱 결제 패키지 설치
  pubspec.lock
  pubspec.yaml
Labels: feat

#360 [Challenge] UT 피드백 반영 - UI 및 기능 수정
  lib/presentation/challenge/challenge_page.dart
  lib/presentation/challenge/widgets/challenge_container.dart
  lib/presentation/challenge/widgets/challenge_intro_mongbi_message_view.dart
  lib/presentation/challenge/widgets/mongbi_dialog.dart
Labels: fix

#363 [Core] 서버와의 통신 속도 최적화
  lib/providers/core_providers.dart
Labels: feat

#364 [Docs] README 업데이트
  README.md
Labels: documentation

#368 [Docs] README 업데이트
  README.md
Labels: documentation

#374 [Alarm] RemoteAlarmDataSource에서 SecureStorageService 직접 호출을 Provider 사용으로 교체
  lib/data/data_sources/remote_alarm_data_source.dart
  lib/providers/alarm_provider.dart
Labels: refactor

#377 [Statistics] RemoteStatisticsDataSource에서 SecureStorageService 직접 호출을 Provider 사용으로 교체
  lib/data/data_sources/remote_statistics_data_source.dart
  lib/providers/statistics_provider.dart
Labels: refactor
