Repository Meezzi/mongbi-app, pull requests merged in 2025-06, with the labels that each got.

#16 빈 폴더를 추가하기 위한 .gitkeep 파일 추가
  lib/data/datasources/.gitkeep
  lib/data/dtos/.gitkeep
  lib/data/repositories/.gitkeep
  lib/domain/entities/.gitkeep
  lib/domain/repositories/.gitkeep
  lib/domain/use_cases/.gitkeep
  lib/presentation/auth/.gitkeep
  lib/presentation/challenge/.gitkeep
  lib/presentation/dream/.gitkeep
  lib/presentation/history/.gitkeep
  lib/presentation/home/.gitkeep
  lib/presentation/onboarding/.gitkeep
  lib/presentation/profile/.gitkeep
  lib/presentation/statistics/.gitkeep
  lib/providers/.gitkeep
Labels: feat

#17 [Dream] 꿈 저장
  .gitignore
  .metadata
  lib/data/data_sources/dream_data_source.dart
  lib/data/data_sources/remote_dream_data_source.dart
  lib/data/datasources/.gitkeep
  lib/data/dtos/.gitkeep
  lib/data/dtos/dream_dto.dart
  lib/data/repositories/.gitkeep
  lib/data/repositories/remote_dream_repository.dart
  lib/domain/entities/.gitkeep
  lib/domain/entities/dream.dart
  lib/domain/repositories/.gitkeep
  lib/domain/repositories/dream_repository.dart
  lib/domain/use_cases/.gitkeep
  lib/domain/use_cases/dream_save_use_case.dart
  lib/main.dart
  lib/presentation/dream/.gitkeep
  lib/providers/.gitkeep
  lib/providers/core_providers.dart
  lib/providers/dream_provider.dart
  pubspec.lock
  pubspec.yaml
  test/data/dream_data_source_test.dart
  test/data/dream_repository_test.dart
  test/domain/dream_save_use_case_test.dart
Labels: feat

#20 [Calendar] 꿈 기록 표시
  assets/fonts/NanumSquareRoundOTFB.otf
  assets/fonts/NanumSquareRoundOTFEB.otf
  assets/fonts/NanumSquareRoundOTFR.otf
  assets/icons/bad.svg
  assets/icons/chevron-down.svg
  assets/icons/good.svg
  assets/icons/ordinary.svg
  assets/icons/very_bad.svg
  assets/icons/very_good.svg
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  lib/core/date_formatter.dart
  lib/core/font.dart
  lib/data/data_sources/history_data_source.dart
  lib/data/data_sources/history_data_source_impl.dart
  lib/data/dtos/history_dto.dart
  lib/domain/entities/history.dart
  lib/domain/repositories/history_repository.dart
  lib/domain/use_cases/fetch_user_dreams_history_use_case.dart
  lib/main.dart
  lib/presentation/history/history_page.dart
  lib/presentation/history/models/calendar_model.dart
  lib/presentation/history/view_models/calendar_view_model.dart
  lib/presentation/history/view_models/history_view_model.dart
  lib/presentation/history/widgets/calendar.dart
  lib/presentation/history/widgets/calendar_drop_down_button.dart
  lib/presentation/history/widgets/history_item.dart
  lib/presentation/history/widgets/history_list.dart
  pubspec.lock
  pubspec.yaml
  test/data/history_data_source_test.dart
  test/domain/fetch_all_history_use_case_test.dart
Labels: feat

#23 [Core] pubspec.lock 오류 수정
  pubspec.lock
Labels: bug

#25 [Auth] 로그인 UI 구현
  assets/images/apple_login.svg
  assets/images/google_login.svg
  assets/images/kakao_login.svg
  assets/images/mongbi.png
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  lib/main.dart
  lib/presentation/auth/.gitkeep
  lib/presentation/auth/social_login_page.dart
  lib/presentation/auth/widgets/apple_login_button_widget.dart
  lib/presentation/auth/widgets/google_login_button_widget.dart
  lib/presentation/auth/widgets/kakao_login_button_widget.dart
  lib/presentation/auth/widgets/last_login_state_weiget.dart
  lib/presentation/auth/widgets/mongbi_image_widget.dart
  lib/presentation/auth/widgets/text_widgets.dart
  pubspec.lock
  pubspec.yaml
Labels: feat

#29 [Calendar] 기록 UI 수정 및 데이터 연동
  assets/icons/chevron-left.svg
  assets/icons/chevron-right.svg
  lib/core/date_formatter.dart
  lib/core/get_responsive_ratio_by_width.dart
  lib/core/get_widget_info.dart
  lib/data/data_sources/history_data_source_impl.dart
  lib/data/dtos/history_dto.dart
  lib/data/repositories/history_repository_impl.dart
  lib/domain/entities/history.dart
  lib/presentation/history/history_key/history_key.dart
  lib/presentation/history/history_page.dart
  lib/presentation/history/models/calendar_model.dart
  lib/presentation/history/view_models/calendar_view_model.dart
  lib/presentation/history/view_models/history_view_model.dart
  lib/presentation/history/widgets/calendar.dart
  lib/presentation/history/widgets/calendar_bottom_sheet.dart
  lib/presentation/history/widgets/calendar_bottom_sheet_month_selector.dart
  lib/presentation/history/widgets/calendar_bottom_sheet_year_selector.dart
  lib/presentation/history/widgets/calendar_cell.dart
  lib/presentation/history/widgets/calendar_change_button.dart
  lib/presentation/history/widgets/calendar_drop_down_button.dart
  lib/presentation/history/widgets/history_app_bar.dart
  lib/presentation/history/widgets/history_body.dart
  lib/presentation/history/widgets/history_item.dart
  lib/presentation/history/widgets/history_list.dart
  lib/presentation/history/widgets/history_notice.dart
  lib/providers/history_provider.dart
  pubspec.lock
  test/domain/fetch_all_history_use_case_test.dart
Labels: feat

#30 [Dream] 꿈 해석 UI 레이아웃 구현
  lib/core/router.dart
  lib/main.dart
  lib/presentation/dream/dream_analysis_loading_page.dart
  lib/presentation/dream/dream_analysis_result_page.dart
  lib/presentation/dream/dream_interpretation_page.dart
  lib/presentation/dream/dream_write_page.dart
  lib/presentation/dream/models/dream_interpretation_state.dart
  lib/presentation/dream/view_models/dream_interpretation_view_model.dart
  lib/presentation/dream/view_models/dream_write_view_model.dart
  lib/presentation/dream/widgets/custom_button.dart
  lib/presentation/dream/widgets/dream_section_card.dart
  lib/presentation/dream/widgets/mongbi_comment_card.dart
  lib/providers/core_providers.dart
  lib/providers/dream_provider.dart
  pubspec.lock
  pubspec.yaml
  test/presentation/dream_interpretation_view_model_test.dart
Labels: feat

#38 [Home] 홈 화면 UI 레이아웃 구현
  assets/icons/bell.svg
  assets/icons/home_filled.svg
  assets/icons/home_outlined.svg
  assets/icons/home_purple_filled.svg
  assets/icons/home_purple_outlined.svg
  assets/icons/record_filled.svg
  assets/icons/record_outlined.svg
  assets/icons/record_purple_filled.svg
  assets/icons/record_purple_outlined.svg
  assets/icons/statistics_filled.svg
  assets/icons/statistics_outlined.svg
  assets/icons/statistics_purple_filled.svg
  assets/icons/statistics_purple_outlined.svg
  assets/icons/user_filled.svg
  assets/icons/user_outlined.svg
  assets/icons/user_purple_filled.svg
  assets/icons/user_purple_outlined.svg
  assets/images/home_cloude.svg
  assets/images/home_star.png
  lib/core/main_scaffold.dart
  lib/core/router.dart
  lib/presentation/home/.gitkeep
  lib/presentation/home/home_page.dart
  lib/presentation/home/widgets/speech_bubble.dart
  pubspec.yaml
Labels: feat

#46 [Splash] 스플래시 화면 구현
  assets/images/splash_bg.svg
  assets/images/splash_mongbi.png
  assets/images/splash_mongbi.svg
  assets/images/star.png
  lib/core/router.dart
  lib/presentation/splash/splash_page.dart
  pubspec.yaml
Labels: feat

#45 [Terms] 약관 동의 화면 및 기능 구현
  assets/icons/checkbox_checked.svg
  assets/icons/checkbox_unchecked.svg
  assets/icons/chevron_right.svg
  devtools_options.yaml
  lib/core/get_responsive_ratio_by_width.dart
  lib/data/data_sources/remote_terms_data_source.dart
  lib/data/data_sources/terms_data_soure.dart
  lib/data/dtos/terms_aggrement_dto.dart
  lib/data/dtos/terms_dto.dart
  lib/data/repositories/remote_dream_repository.dart
  lib/data/repositories/remote_terms_repository.dart
  lib/domain/entities/terms.dart
  lib/domain/repositories/terms_repository.dart
  lib/domain/use_cases/agree_to_terms_usecase.dart
  lib/domain/use_cases/fetch_terms_use_case.dart
  lib/presentation/auth/social_login_page.dart
  lib/presentation/terms/terms_inner_page.dart
  lib/presentation/terms/viewmodels/terms_state.dart
  lib/presentation/terms/viewmodels/terms_viewmodels.dart
  lib/presentation/terms/widgets/terms_bottom_sheet_layout_widget.dart
  lib/presentation/terms/widgets/terms_button_widget.dart
  lib/presentation/terms/widgets/terms_checkbox_widget.dart
  lib/presentation/terms/widgets/terms_custom_checkbox.widget.dart
  lib/presentation/terms/widgets/terms_text_widget.dart
  lib/providers/core_providers.dart
  lib/providers/terms_provider.dart
  pubspec.yaml
Labels: feat

#49 [Splash]애니메이션 속도 조정
  lib/presentation/splash/splash_page.dart
Labels: bug

#51 [Home] 배경음악 재생 오류
  lib/providers/background_music_provider.dart
Labels: bug

#53 [Dream] 꿈 해석 결과가 나옴과 동시에 저장 로직
  lib/domain/use_cases/analyze_and_save_dream_use_case.dart
  lib/domain/use_cases/save_dream_use_case.dart
  lib/presentation/dream/dream_interpretation_page.dart
  lib/presentation/dream/view_models/dream_interpretation_view_model.dart
  lib/presentation/dream/view_models/dream_write_view_model.dart
  lib/providers/dream_provider.dart
  test/domain/analyze_and_save_dream_use_case_test.dart
  test/domain/analyze_dream_use_case_test.dart
  test/domain/dream_save_use_case_test.dart
  test/presentation/dream_interpretation_view_model_test.dart
  test/presentation/dream_write_view_model_test.dart
Labels: feat

#57 [Statistics] 꿈 분석에 대한 통계 UI 구현
  assets/icons/cancel.svg
  assets/icons/info.svg
  ios/Podfile
  ios/Runner/Info.plist
  lib/core/date_formatter.dart
  lib/core/main_scaffold.dart
  lib/core/router.dart
  lib/presentation/statistics/models/statistics_model.dart
  lib/presentation/statistics/statistics_key/statistics_key.dart
  lib/presentation/statistics/statistics_page.dart
  lib/presentation/statistics/view_models/statistics_view_model.dart
  lib/presentation/statistics/widgets/common_box.dart
  lib/presentation/statistics/widgets/custom_fl_dot_painter.dart
  lib/presentation/statistics/widgets/dream_frequency_card.dart
  lib/presentation/statistics/widgets/dream_mood_distribution.dart
  lib/presentation/statistics/widgets/dream_mood_distribution_percent.dart
  lib/presentation/statistics/widgets/dream_mood_distribution_pie_chart.dart
  lib/presentation/statistics/widgets/dream_type_mood_state.dart
  lib/presentation/statistics/widgets/dream_type_mood_state_row.dart
  lib/presentation/statistics/widgets/gift_frequency_card.dart
  lib/presentation/statistics/widgets/month_statistics.dart
  lib/presentation/statistics/widgets/month_year_picker.dart
  lib/presentation/statistics/widgets/month_year_picker_button.dart
  lib/presentation/statistics/widgets/mood_state_info_modal.dart
  lib/presentation/statistics/widgets/psychology_keyword_chart.dart
  lib/presentation/statistics/widgets/tab_bar_title.dart
  lib/presentation/statistics/widgets/year_statistics.dart
  pubspec.yaml
Labels: feat

#63 [Home] 몽비 애니메이션
  lib/presentation/common/floating_animation_widget.dart
  lib/presentation/home/home_page.dart
  lib/presentation/splash/splash_page.dart
Labels: feat

#71 [Dream] 사용자 ID 연결
  lib/data/repositories/remote_dream_repository.dart
  lib/domain/repositories/dream_repository.dart
  lib/domain/use_cases/analyze_and_save_dream_use_case.dart
  lib/domain/use_cases/analyze_dream_use_case.dart
  lib/domain/use_cases/save_dream_use_case.dart
  lib/presentation/dream/view_models/dream_write_view_model.dart
Labels: feat

#76 [Terms] 바텀시트 외부 영역 터치시 바텀 시트 내려가는 현상 수정
  lib/presentation/auth/social_login_page.dart
Labels: fix

#77 [Terms]약관 동의시 SharedPreferences에 저장된 userIDX를 불러와 상태저장
  lib/presentation/terms/widgets/terms_bottom_sheet_layout_widget.dart
Labels: fix

#78 [Home] 홈 화면 UI 레이아웃 수정
  lib/core/main_scaffold.dart
  lib/presentation/home/home_page.dart
  lib/presentation/home/widgets/mongbi_message_list.dart
Labels: feat

#80 [Home] 홈 화면 구름 이미지 변경
  assets/images/home_cloude.svg
  lib/core/main_scaffold.dart
Labels: feat

#81 [Remind] 리마인드 알림 기능 구현
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/drawable/ic_mongbi_icon.png
  assets/icons/back-arrow.svg
  assets/images/remind_bell.webp
  ios/Runner/AppDelegate.swift
  lib/core/router.dart
  lib/main.dart
  lib/presentation/remind/remind_time_setting_page.dart
  lib/presentation/remind/remind_time_time_setting_page.dart
  lib/presentation/remind/view_model/remind_time_setting_view_model.dart
  lib/presentation/remind/widgets/remind_time_setting_button_widget.dart
  lib/presentation/remind/widgets/remind_time_setting_image_widget.dart
  lib/presentation/remind/widgets/remind_time_setting_text_widget.dart
  lib/presentation/remind/widgets/remind_time_setting_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: feat

#82 [Auth] 네이버& 카카오 로그아웃 기능 구현 완료
  lib/core/router.dart
  lib/presentation/auth/viewmodels/auth_view_model.dart
  lib/presentation/setting/profile_setting_page.dart
  lib/presentation/setting/widgets/logout_confirm_dialog.dart
Labels: feat

#92 [Statistics] SliverAppBar 오류 수정
  lib/presentation/statistics/statistics_page.dart
  lib/presentation/statistics/widgets/tab_bar_title.dart
Labels: bug, fix

#94 [History] History 피드백 적용
  lib/data/data_sources/remote_history_data_source.dart
  lib/data/repositories/remote_history_repository.dart
  lib/presentation/history/widgets/calendar_bottom_sheet_month_selector.dart
  lib/presentation/history/widgets/history_body.dart
  lib/presentation/history/widgets/history_list.dart
  lib/providers/history_provider.dart
  test/data/history_data_source_test.dart
Labels: fix

#93 [Statistics] 해당 월별/년도별 통계 자료가 없을 경우 꿈 작성 페이지로 유도하는 스낵바 표시
  lib/core/main_scaffold.dart
  lib/presentation/statistics/statistics_key/statistics_key.dart
  lib/presentation/statistics/widgets/custom_snack_bar.dart
  lib/presentation/statistics/widgets/month_statistics.dart
  lib/presentation/statistics/widgets/month_year_picker.dart
  lib/presentation/statistics/widgets/year_statistics.dart
Labels: feat

#99 [Core] 라우팅 수정
  lib/core/router.dart
  lib/presentation/remind/remind_time_time_setting_page.dart
  lib/presentation/setting/nickname_input_page.dart
Labels: fix

#103 [Onbording] 몽비 만나러 가기 버튼 잘리는 현상 수정
  lib/presentation/onboarding/widgets/onbording_skip_button_widget.dart
Labels: fix

#106 [Statistics] 꿈 작성 페이지로 유도하는 스낵바 표시 조건 변경
  lib/core/route_observer.dart
  lib/core/router.dart
  lib/data/dtos/statistics_dto.dart
  lib/data/repositories/remote_statistics_repository.dart
  lib/presentation/statistics/statistics_page.dart
  lib/presentation/statistics/widgets/custom_snack_bar.dart
  lib/presentation/statistics/widgets/month_statistics.dart
  lib/presentation/statistics/widgets/month_year_picker.dart
  lib/presentation/statistics/widgets/mood_state_info_modal.dart
  lib/presentation/statistics/widgets/year_statistics.dart
Labels: feat

#114 [Alarm] 알림 페이지 TDD 작성
  lib/data/data_sources/alarm_data_source.dart
  lib/data/data_sources/remote_alarm_data_source.dart
  lib/data/dtos/alarm_dto.dart
  lib/data/repositories/remote_alarm_repository.dart
  lib/domain/entities/alarm.dart
  lib/domain/repositories/alarm_repository.dart
  test/data/alarm_data_source_test.dart
  test/data/alarm_repository_test.dart
Labels: feat

#129 [Dream] 꿈 기분 선택 점수 오류 수정
  lib/presentation/dream/view_models/dream_write_view_model.dart
Labels: bug

#136 [Core] 공통 버튼 - 폰트 미적용 오류 해결
  lib/presentation/common/filled_button_widget.dart
  lib/presentation/common/ghost_button_widget.dart
Labels: fix

#138 [Dream] QA 테스트 후, 꿈 작성 화면 UI 레이아웃 수정
  lib/presentation/dream/dream_write_page.dart
  lib/presentation/dream/widgets/dream_content_input.dart
  lib/presentation/dream/widgets/submit_dream_button.dart
Labels: feat

#140 [Setting] QA 피드백 적용 - UI 변경
  lib/core/main_scaffold.dart
  lib/presentation/setting/alarm_setting_page.dart
  lib/presentation/setting/widgets/setting_rounded_list_tile_item.dart
  lib/presentation/setting/widgets/setting_toggle_switch.dart
  lib/presentation/setting/widgets/setting_user_info_header.dart
Labels: feat

#142 [Core] 앱 id 변경
  .gitignore
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/AppDelegate.swift
  ios/Runner/Info.plist
  pubspec.lock
  pubspec.yaml
Labels: feat

#143 [Challenage] 챌린지 제안
  lib/core/remove_html_tags.dart
  lib/core/router.dart
  lib/data/data_sources/dream_save_data_source.dart
  lib/data/data_sources/fetch_challenge_data_source.dart
  lib/data/data_sources/remote_dream_data_source.dart
  lib/data/data_sources/remote_fetch_challenge_data_source.dart
  lib/data/data_sources/remote_save_challenge_data_source.dart
  lib/data/data_sources/save_challenge_data_source.dart
  lib/data/dtos/challenge_dto.dart
  lib/data/repositories/remote_challenge_repository.dart
  lib/data/repositories/remote_dream_repository.dart
  lib/domain/entities/challenge.dart
  lib/domain/entities/dream.dart
  lib/domain/repositories/challenge_repository.dart
  lib/domain/repositories/dream_repository.dart
  lib/domain/use_cases/analyze_and_save_dream_use_case.dart
  lib/domain/use_cases/fetch_challenge_use_case.dart
  lib/domain/use_cases/save_challenge_use_case.dart
  lib/domain/use_cases/save_dream_use_case.dart
  lib/presentation/challenge/.gitkeep
  lib/presentation/challenge/challenge_intro_page.dart
  lib/presentation/challenge/challenge_page.dart
  lib/presentation/challenge/view_models/challenge_view_model.dart
  lib/presentation/challenge/widgets/challenge_container.dart
  lib/presentation/challenge/widgets/challenge_intro_mongbi_message_view.dart
  lib/presentation/challenge/widgets/mongbi_dialog.dart
  lib/presentation/common/action_button_row.dart
  lib/presentation/common/custom_snack_bar.dart
  lib/presentation/dream/dream_interpretation_page.dart
  lib/presentation/dream/models/dream_interpretation_state.dart
  lib/presentation/dream/view_models/dream_interpretation_view_model.dart
  lib/providers/challenge_provider.dart
  test/data/challenge_repository_test.dart
  test/data/fetch_challenge_data_source_test.dart
  test/data/save_challenge_data_source_test.dart
  test/domain/challenge_use_case_test.dart
  test/domain/save_challenge_use_case_test.dart
Labels: feat

#148 [Dream] 꿈 재작성할 때 꿈 기분 리셋
  lib/presentation/dream/view_models/dream_write_view_model.dart
  lib/providers/dream_provider.dart
Labels: bug

#152 [Auth]애플로그인 추가
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/GoogleService-Info.plist
  ios/Runner/Info.plist
  ios/Runner/Runner.entitlements
  lib/data/data_sources/apple_auth_data_source.dart
  lib/data/data_sources/remote_apple_auth_data_source.dart
  lib/data/repositories/remote_auth_repository.dart
  lib/domain/repositories/auth_repository.dart
  lib/domain/use_cases/login_with_apple.dart
  lib/main.dart
  lib/presentation/auth/social_login_page.dart
  lib/presentation/auth/viewmodels/auth_view_model.dart
  lib/presentation/dream/dream_interpretation_page.dart
  lib/presentation/remind/remind_time_setting_page.dart
  lib/presentation/remind/remind_time_time_setting_page.dart
  lib/presentation/remind/view_model/remind_time_setting_view_model.dart
  lib/presentation/setting/profile_setting_page.dart
  lib/presentation/setting/setting_page.dart
  lib/providers/auth_provider.dart
  pubspec.lock
  pubspec.yaml
Labels: feat

#156 [Auth] JWT 토큰 인증 반영 및 최신화
  lib/core/auth_interceptor.dart
  lib/core/secure_storage_service.dart
  lib/data/data_sources/remote_history_data_source.dart
  lib/data/data_sources/remote_kakao_auth_data_source.dart
  lib/data/data_sources/remote_naver_auth_data_source.dart
  lib/data/data_sources/remote_statistics_data_source.dart
  lib/data/data_sources/remote_user_info_data_source.dart
  lib/data/data_sources/user_info_data_source.dart
  lib/data/repositories/remote_user_info_reposiotory.dart
  lib/domain/repositories/user_info_repository.dart
  lib/domain/use_cases/get_user_info_use_case.dart
  lib/domain/use_cases/login_with_kakao.dart
  lib/main.dart
  lib/presentation/auth/viewmodels/auth_view_model.dart
  lib/presentation/dream/view_models/dream_write_view_model.dart
  lib/presentation/setting/nickname_input_page.dart
  lib/presentation/setting/profile_setting_page.dart
  lib/presentation/setting/setting_page.dart
  lib/presentation/setting/view_models/nickname_setting_view_model.dart
  lib/presentation/splash/splash_page.dart
  lib/presentation/splash/view_models/splash_state.dart
  lib/presentation/splash/view_models/splash_status.dart
  lib/presentation/splash/view_models/splash_view_model.dart
  lib/presentation/terms/terms_inner_page.dart
  lib/presentation/terms/viewmodels/terms_state.dart
  lib/presentation/terms/viewmodels/terms_viewmodels.dart
  lib/presentation/terms/widgets/terms_bottom_sheet_layout_widget.dart
  lib/presentation/terms/widgets/terms_button_widget.dart
  lib/presentation/terms/widgets/terms_custom_checkbox.widget.dart
  lib/presentation/terms/widgets/terms_text_widget.dart
  lib/providers/background_music_provider.dart
  lib/providers/core_providers.dart
  lib/providers/nickname_provider.dart
  lib/providers/user_info_provider.dart
  pubspec.lock
  pubspec.yaml
Labels: feat

#155 [Home] QA 피드백 적용 - UI 변경
  ios/Podfile.lock
  lib/core/main_scaffold.dart
  lib/core/no_transition_page.dart
  lib/core/router.dart
Labels: feat

#157 [Alarm] 알림 API 연동
  lib/core/date_formatter.dart
  lib/core/main_scaffold.dart
  lib/data/data_sources/alarm_data_source.dart
  lib/data/data_sources/remote_alarm_data_source.dart
  lib/data/dtos/alarm_dto.dart
  lib/data/repositories/remote_alarm_repository.dart
  lib/domain/entities/alarm.dart
  lib/domain/repositories/alarm_repository.dart
  lib/domain/use_cases/fetch_alarms_use_case.dart
  lib/domain/use_cases/update_is_read_status_use_case.dart
  lib/presentation/alarm/alarm_page.dart
  lib/presentation/alarm/models/alarm_model.dart
  lib/presentation/alarm/view_models/alarm_view_model.dart
  lib/presentation/alarm/widgets/alarm_app_bar.dart
  lib/presentation/alarm/widgets/alarm_body.dart
  lib/presentation/alarm/widgets/alarm_item.dart
  lib/presentation/alarm/widgets/alarm_type.dart
  lib/presentation/alarm/widgets/delete_modal.dart
  lib/providers/alarm_provider.dart
  test/data/alarm_data_source_test.dart
  test/data/alarm_repository_test.dart
Labels: feat, fix

#162 [Statistics] QA 2차 피드백 디자인 수정
  lib/presentation/history/widgets/calendar_bottom_sheet_month_selector.dart
  lib/presentation/statistics/statistics_page.dart
Labels: fix

#168 [Dream] 꿈을 하루에 두 번만 작성할 수 있게 로직 변경
  lib/core/main_scaffold.dart
  lib/data/data_sources/dream_check_data_source.dart
  lib/data/data_sources/remote_dream_check_data_source.dart
  lib/data/repositories/remote_dream_repository.dart
  lib/domain/repositories/dream_repository.dart
  lib/domain/use_cases/can_write_dream_today_use_case.dart
  lib/presentation/challenge/challenge_page.dart
  lib/presentation/common/custom_snack_bar.dart
  lib/providers/dream_provider.dart
Labels: feat

#173 [Challenge] 챌린지 마감 시간 오류
  ios/Podfile.lock
  lib/core/calculate_time_remaining.dart
  pubspec.lock
Labels: bug

#181 [Setting] 리마인드 토글 동기화 작업
  lib/presentation/remind/remind_time_time_setting_page.dart
  lib/presentation/remind/view_model/remind_time_setting_view_model.dart
  lib/presentation/setting/alarm_setting_page.dart
  lib/presentation/setting/view_models/alarm_setting_view_model.dart
Labels: feat

#182 [Dream] QA 피드백 적용 - UI 변경
  lib/presentation/dream/dream_interpretation_page.dart
  lib/presentation/dream/widgets/dream_section_card.dart
Labels: feat

#188 [Home] 챌린지 Bottom Sheet 텍스트 수정
  lib/presentation/home/widgets/completion_bottom_sheet.dart
Labels: bug

#192 [Challenge] 챌린지 시간 표시 에러
  lib/core/challenge_dead_line_manager.dart
  lib/main.dart
Labels: bug

#198 [Setting] QA 피드백 적용 - UI 변경
  lib/presentation/setting/alarm_setting_page.dart
  lib/presentation/setting/profile_setting_page.dart
Labels: feat

#199 [Dream] QA 피드백 적용 - UI 변경
  lib/presentation/dream/dream_interpretation_page.dart
Labels: fix

#201 [Alarm] 알림 아이콘, 페이지 숨김 처리
  lib/core/main_navi_tab_bar.dart
  lib/core/main_scaffold.dart
  lib/core/set_up_fcm.dart
  lib/presentation/statistics/widgets/month_statistics.dart
Labels: fix

#203 [Auth] 애플로그인 실패 현상 해결
  lib/data/data_sources/remote_apple_auth_data_source.dart
Labels: fix

#204 [Setting] 닉네임 설정 leading 이 두 개 나타나는 오류
  lib/presentation/dream/dream_interpretation_page.dart
  lib/presentation/setting/nickname_input_page.dart
Labels: feat

#209 style: 리딩 버튼 위치 수정
  lib/presentation/remind/remind_time_setting_page.dart
  lib/presentation/remind/remind_time_time_setting_page.dart
Labels: fix

#213 [Auth] 애플 로그인 로그아웃 기능 추가
  lib/presentation/auth/viewmodels/auth_view_model.dart
  lib/presentation/setting/widgets/logout_account_modal.dart
Labels: feat

#219 [Dream] 꿈 해석 후, 다시 작성
  lib/core/router.dart
  lib/presentation/dream/dream_analysis_loading_page.dart
  lib/presentation/dream/dream_analysis_result_page.dart
  lib/presentation/dream/dream_interpretation_page.dart
  lib/presentation/dream/dream_write_page.dart
  lib/presentation/dream/models/dream_interpretation_state.dart
  lib/presentation/dream/view_models/dream_write_view_model.dart
Labels: feat

#224 [Auth] 로그인 예외 처리
  lib/core/exceptions/auth_custom_exception.dart
  lib/data/data_sources/remote_apple_auth_data_source.dart
  lib/data/data_sources/remote_kakao_auth_data_source.dart
  lib/data/data_sources/remote_naver_auth_data_source.dart
  lib/presentation/auth/social_login_page.dart
  lib/presentation/auth/viewmodels/auth_view_model.dart
Labels: bug

#228 [Auth]애플로그인 정보 못받아오는 버그 수정
  lib/domain/use_cases/login_with_apple.dart
  lib/presentation/auth/viewmodels/auth_view_model.dart
Labels: fix

#244 [Statistics] 통계 없을 시 '꿈 작성' 요청 스낵바 띄우기
  lib/core/main_navi_tab_bar.dart
  lib/core/main_scaffold.dart
  lib/presentation/statistics/statistics_key/statistics_key.dart
  lib/presentation/statistics/statistics_page.dart
  lib/presentation/statistics/widgets/custom_snack_bar.dart
  lib/presentation/statistics/widgets/month_statistics.dart
  lib/presentation/statistics/widgets/month_year_picker.dart
  lib/presentation/statistics/widgets/tab_bar_title.dart
  lib/presentation/statistics/widgets/year_statistics.dart
  lib/providers/statistics_provider.dart
Labels: feat

#249 [Statistics] UT 피드백 반영 - UI 수정
  lib/presentation/statistics/statistics_page.dart
  lib/presentation/statistics/widgets/common_box.dart
  lib/presentation/statistics/widgets/custom_snack_bar.dart
  lib/presentation/statistics/widgets/dream_frequency_card.dart
  lib/presentation/statistics/widgets/dream_mood_distribution.dart
  lib/presentation/statistics/widgets/dream_mood_distribution_percent.dart
  lib/presentation/statistics/widgets/dream_mood_distribution_pie_chart.dart
  lib/presentation/statistics/widgets/dream_type_mood_state.dart
  lib/presentation/statistics/widgets/dream_type_mood_state_row.dart
  lib/presentation/statistics/widgets/gift_frequency_card.dart
  lib/presentation/statistics/widgets/month_statistics.dart
  lib/presentation/statistics/widgets/month_year_picker.dart
  lib/presentation/statistics/widgets/month_year_picker_button.dart
  lib/presentation/statistics/widgets/mood_state_info_modal.dart
  lib/presentation/statistics/widgets/psychology_keyword_chart.dart
  lib/presentation/statistics/widgets/tab_bar_title.dart
  lib/presentation/statistics/widgets/year_statistics.dart
Labels: fix

#253 [Core] Univarsal Link 추가
  ios/Flutter/Release.xcconfig
  ios/Runner/Info.plist
  ios/Runner/Runner.entitlements
Labels: bug

#257 [Remind] 리마인드 푸시 알림 문구 수정
  lib/presentation/remind/view_model/remind_time_setting_view_model.dart
Labels: fix

#264 [Challenge] 챌린지 중복 저장 오류
  lib/presentation/challenge/challenge_page.dart
Labels: bug

#266 [Remind] 리마인드 에러 수정
  lib/main.dart
  lib/presentation/remind/remind_time_setting_page.dart
  lib/presentation/setting/alarm_setting_page.dart
Labels: fix

#272 [Setting] 배경음악 오류 수정
  lib/main.dart
  lib/presentation/setting/setting_page.dart
Labels: bug

#275 [Setting] 고겍센터 버튼 위치 변경
  lib/presentation/setting/setting_page.dart
Labels: fix

#277 [Remind] RemindTimeSettingPage에서 경로 이동 방식을 go()에서 push()로 변경
  lib/presentation/remind/remind_time_setting_page.dart
  lib/presentation/terms/terms_inner_page.dart
Labels: fix

#279 [Setting] 네비게이션 방식 수정 - 홈으로 돌아가기 및 닉네임 입력 페이지에서 알림 설정 페이지로의 이동 방식 변경
  lib/presentation/remind/remind_time_setting_page.dart
  lib/presentation/setting/nickname_input_page.dart
Labels: fix

#282 [Setting]알림 권한 요청 및 상태 관리 개선
  lib/presentation/setting/alarm_setting_page.dart
Labels: fix

#284 [Setting]알림 권한 요청 설정을 활성화하여 사용자 경험 개선
  lib/presentation/remind/view_model/remind_time_setting_view_model.dart
Labels: fix

#287 [Setting] 알림 권한 요청 로직 개선 및 Firebase Analytics 이벤트 제거
  lib/presentation/remind/remind_time_time_setting_page.dart
  lib/presentation/remind/view_model/remind_time_setting_view_model.dart
  lib/presentation/setting/alarm_setting_page.dart
Labels: fix

#291 [Core] iPad 지원 비활성화
  ios/Runner/Info.plist
Labels: feat
